// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function map(o, fn) {
  if (o !== undefined) {
    return Caml_option.some(Curry._1(fn, Caml_option.valFromOption(o)));
  }
  
}

export {
  map ,
}
/* No side effect */
